"""SPIR-V from glslc, as the word-count-prefixed arrays spirv_h.py writes.

For the shaders written in GLSL rather than HLSL: the present overlay, which
has no D3D counterpart. Needs glslc, from the Vulkan SDK or the Android NDK's
shader-tools.

    python glsl_h.py <glslc> overlay.vert overlay_VS ../shadersvk/overlay_VS.h
"""

import struct
import subprocess
import sys
import tempfile
import os


def main():
    glslc, src, name, out = sys.argv[1:5]
    with tempfile.TemporaryDirectory() as tmp:
        spv = os.path.join(tmp, "out.spv")
        subprocess.run([glslc, "-O", "--target-env=vulkan1.3", src, "-o", spv], check=True)
        data = open(spv, "rb").read()
    words = struct.unpack("<%dI" % (len(data) // 4), data)
    with open(out, "w", newline="\n") as f:
        f.write("// Generated by glsl_h.py from %s. Do not edit.\n" % os.path.basename(src))
        f.write("const unsigned int %s[] = {\n\t%d,\n" % (name, len(words)))
        for i in range(0, len(words), 8):
            f.write("\t" + " ".join("0x%08x," % w for w in words[i:i + 8]) + "\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
