# A SPIR-V module from dxc, as the C header the Vulkan backend includes.
#
#     python spirv_h.py shader.spv name out.h
#
# The header is one array of 32-bit words named `name`, and word 0 is the number
# of SPIR-V words that follow it. createVertexShader takes a bare pointer, the
# same as the D3D backends do, so the length has to travel inside the array.
#
# **Stage interface locations are renumbered by semantic.** Direct3D links a
# vertex shader's outputs to a pixel shader's inputs by semantic name, and the
# shaders here are written for that: a vertex shader may write TEXCOORD2 that
# its pixel shader never reads, and the two declare their structs in whatever
# order suits them. Vulkan links by location, and dxc hands locations out in
# declaration order, so the same pair would come out mismatched. Every vertex
# input, vertex output and pixel input is given the location LOCATIONS names
# for its semantic, which is also how the backend finds a vertex input from a
# D3D9 declaration element without asking the shader.
#
# The semantic strings dxc writes for -fspv-reflect are what this reads, and
# they are removed along with the extensions that declare them: a driver is
# entitled to refuse a module that enables an extension it does not know.
import struct, sys

# Keep in step with vkLocationForUsage in vkshader.cpp.
LOCATIONS = {
    'POSITION0': 0,
    'NORMAL0': 1,
    'COLOR0': 2,
    'COLOR1': 3,
    'BLENDWEIGHT0': 4,
    'BLENDINDICES0': 5,
    'TEXCOORD0': 6,
    'TEXCOORD1': 7,
    'TEXCOORD2': 8,
    'TEXCOORD3': 9,
    'TEXCOORD4': 10,
    'TEXCOORD5': 11,
    'TEXCOORD6': 12,
    'TEXCOORD7': 13,
    'TANGENT0': 14,
    'BINORMAL0': 15,
}

OP_EXTENSION = 10
OP_ENTRY_POINT = 15
OP_VARIABLE = 59
OP_DECORATE = 71
# OpDecorateString, and OpDecorateStringGOOGLE: the same instruction as it was
# numbered before SPIR-V 1.4, which is what dxc writes for vulkan1.1.
OP_DECORATE_STRING = (1087, 5632)
DEC_LOCATION = 30
DEC_USER_SEMANTIC = 5635
DEC_USER_TYPE = 5636
SC_INPUT = 1
SC_OUTPUT = 3
MODEL_VERTEX = 0
MODEL_FRAGMENT = 4
DROPPED_EXTENSIONS = ('SPV_GOOGLE_hlsl_functionality1', 'SPV_GOOGLE_user_type')


def literal_string(words):
    raw = struct.pack('<%dI' % len(words), *words)
    return raw[:raw.index(b'\0')].decode('utf-8')


def canonical(semantic):
    s = semantic.upper()
    return s if not s or s[-1].isdigit() else s + '0'


def main():
    src, name, out = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(src, 'rb').read()
    words = list(struct.unpack('<%dI' % (len(data) // 4), data))
    if words[0] != 0x07230203:
        sys.exit('%s: not a SPIR-V module' % src)

    # First pass: what each variable is.
    insts = []
    i = 5
    while i < len(words):
        count = words[i] >> 16
        insts.append((i, words[i] & 0xFFFF, count))
        i += count

    model = None
    storage = {}
    semantic = {}
    for at, op, count in insts:
        ops = words[at+1:at+count]
        if op == OP_ENTRY_POINT:
            model = ops[0]
        elif op == OP_VARIABLE:
            storage[ops[1]] = ops[2]
        elif op in OP_DECORATE_STRING and ops[1] == DEC_USER_SEMANTIC:
            semantic[ops[0]] = literal_string(ops[2:])
    if model not in (MODEL_VERTEX, MODEL_FRAGMENT):
        sys.exit('%s: entry point is neither a vertex nor a fragment shader' % src)

    def renumbered(var):
        sc = storage.get(var)
        if sc == SC_INPUT:
            return True
        return sc == SC_OUTPUT and model == MODEL_VERTEX

    # Second pass: rewrite locations, drop the reflection.
    result = words[:5]
    for at, op, count in insts:
        ops = words[at+1:at+count]
        if op == OP_EXTENSION and literal_string(ops) in DROPPED_EXTENSIONS:
            continue
        if op in OP_DECORATE_STRING and ops[1] in (DEC_USER_SEMANTIC, DEC_USER_TYPE):
            continue
        if op == OP_DECORATE and ops[1] == DEC_LOCATION and renumbered(ops[0]):
            sem = canonical(semantic.get(ops[0], ''))
            if sem not in LOCATIONS:
                sys.exit('%s: no location for semantic %r' % (src, sem))
            result += [words[at], ops[0], DEC_LOCATION, LOCATIONS[sem]]
            continue
        result += words[at:at+count]

    lines = ['// Generated by spirv_h.py from dxc output. Do not edit.',
             'const unsigned int %s[] = {' % name,
             '\t%d,' % (len(result))]
    for j in range(0, len(result), 8):
        lines.append('\t' + ', '.join('0x%08x' % w for w in result[j:j+8]) + ',')
    lines.append('};')
    open(out, 'w', newline='\n').write('\n'.join(lines) + '\n')


main()
